/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job.work.management.system;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sunny
 */
public class Dashboard extends javax.swing.JFrame {
    
    Connection conn = null, connect = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public void con() throws UnknownHostException, SocketException {
        try {
            connect = javaconnect.ConnectDB();
            if (connect == null) {
                lblConnectionStatus.setText( "OFFLINE" );
                lblConnectionStatus.setForeground( Color.RED );
            } else {
                lblConnectionStatus.setText( "ONLINE" );
                lblConnectionStatus.setForeground( Color.GREEN );
            }            
        } finally {
            if (connect != null) try {
                connect.close();
            } catch (SQLException e) {
            }
        }
        
        InetAddress ip = InetAddress.getLocalHost();
        lblIPAddress.setText( "IP ADDRESS IS : " + ip );        
    }

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        try {
            conn = javaconnect.ConnectDB();
        } catch (UnknownHostException e) {
            System.out.println( e );
        }
        this.setIconImage( new ImageIcon( getClass().getResource( "LOGO.jpg" ) ).getImage() );
    }
    
    public void CurrentDate() {        
        Thread clock;
        clock = new Thread() {
            @Override
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
//                    int month=cal.get(Calendar.MONTH);
//                    int day=cal.get(Calendar.DAY_OF_MONTH);
//                    int year=cal.get(Calendar.YEAR);
//                    lblDate.setText(day+"-"+month+"-"+year);
                    LocalDate myDateObj = LocalDate.now();
                    DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern( "dd/MM/yyyy" );
                    String formatedDate = myDateObj.format( myFormatObj );
                    lblDate.setText( "" + formatedDate );
                    
                    int second = cal.get( Calendar.SECOND );
                    int minute = cal.get( Calendar.MINUTE );
                    int hour = cal.get( Calendar.HOUR );
                    String AM_PM = cal.get( Calendar.AM_PM ) == 0 ? "AM" : "PM";
                    lblTime.setText( hour + ":" + minute + ":" + second + " " + AM_PM );                    
                    try {
                        sleep( 1500 );
                    } catch (InterruptedException ex) {
                        //Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        con();
                    } catch (UnknownHostException | SocketException ex) {
                        Logger.getLogger( Dashboard.class.getName() ).log( Level.SEVERE, null, ex );
                    }
                }
            }
        };
        clock.start();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblConnectionStatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblIPAddress = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCompanyDetails = new javax.swing.JMenu();
        mnuManageCompanyDetails = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        mnuClients = new javax.swing.JMenu();
        mnuManageClient = new javax.swing.JMenuItem();
        mnuProducts = new javax.swing.JMenu();
        mnuManageProduct = new javax.swing.JMenuItem();
        mnuProcess = new javax.swing.JMenu();
        mnuManageProcess = new javax.swing.JMenuItem();
        mnuMaterial = new javax.swing.JMenu();
        mnuManageMaterial = new javax.swing.JMenuItem();
        mnuJobOrder = new javax.swing.JMenu();
        mnuCreateJobOrderMaster = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnuSearchJobOrder = new javax.swing.JMenuItem();
        mnuQuotations = new javax.swing.JMenu();
        mnuCreateQuotation = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuManageQuotation = new javax.swing.JMenuItem();
        mnuInvoices = new javax.swing.JMenu();
        mnuCreateInvoice = new javax.swing.JMenuItem();
        mnuSearchInvoice1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuCreateInvoice2 = new javax.swing.JMenuItem();
        mnuSearchInvoice2 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnuProformaInvoice = new javax.swing.JMenuItem();
        mnuSearchProformaInvoice = new javax.swing.JMenuItem();
        mnuChallan = new javax.swing.JMenu();
        mnuCreateChallan = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuManageChallan = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuLicenseDetails = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Satyam Industries - Job Work Management  System * Developed By CODERS TECHNOLOGIES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/dashlogo_transparent.png"))); // NOI18N
        jLabel1.setText("JOB WORK MANAGEMENT SYSTEM");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROPRIETARY SOFTWARE LICENSED TO : PRIYESH AGARWAL");

        lblConnectionStatus.setBackground(new java.awt.Color(0, 0, 0));
        lblConnectionStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConnectionStatus.setForeground(java.awt.Color.green);
        lblConnectionStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConnectionStatus.setText("-");
        lblConnectionStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblConnectionStatus.setOpaque(true);
        lblConnectionStatus.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONNECTION STATUS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIME");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATE");

        lblDate.setBackground(new java.awt.Color(0, 0, 0));
        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setForeground(java.awt.Color.green);
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setOpaque(true);

        lblTime.setBackground(new java.awt.Color(0, 0, 0));
        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime.setForeground(java.awt.Color.green);
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setOpaque(true);

        lblIPAddress.setBackground(new java.awt.Color(0, 0, 0));
        lblIPAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblIPAddress.setForeground(java.awt.Color.green);
        lblIPAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIPAddress.setText("------IP ADDRESS------");
        lblIPAddress.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblIPAddress.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1295, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblConnectionStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblIPAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblConnectionStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        mnuCompanyDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/factory_16px.png"))); // NOI18N
        mnuCompanyDetails.setText("Company Details");

        mnuManageCompanyDetails.setText("Manage Company Details");
        mnuManageCompanyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageCompanyDetailsActionPerformed(evt);
            }
        });
        mnuCompanyDetails.add(mnuManageCompanyDetails);
        mnuCompanyDetails.add(jSeparator1);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuCompanyDetails.add(mnuExit);

        jMenuBar1.add(mnuCompanyDetails);

        mnuClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/client_management_16px.png"))); // NOI18N
        mnuClients.setText("Clients");

        mnuManageClient.setText("Manage Client");
        mnuManageClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageClientActionPerformed(evt);
            }
        });
        mnuClients.add(mnuManageClient);

        jMenuBar1.add(mnuClients);

        mnuProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/products_16px.png"))); // NOI18N
        mnuProducts.setText("Products");

        mnuManageProduct.setText("Manage Product");
        mnuManageProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageProductActionPerformed(evt);
            }
        });
        mnuProducts.add(mnuManageProduct);

        jMenuBar1.add(mnuProducts);

        mnuProcess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/process_16px.png"))); // NOI18N
        mnuProcess.setText("Process");

        mnuManageProcess.setText("Manage Process");
        mnuManageProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageProcessActionPerformed(evt);
            }
        });
        mnuProcess.add(mnuManageProcess);

        jMenuBar1.add(mnuProcess);

        mnuMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/material_16px.png"))); // NOI18N
        mnuMaterial.setText("Material");

        mnuManageMaterial.setText("Manage Material");
        mnuManageMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageMaterialActionPerformed(evt);
            }
        });
        mnuMaterial.add(mnuManageMaterial);

        jMenuBar1.add(mnuMaterial);

        mnuJobOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/job_16px.png"))); // NOI18N
        mnuJobOrder.setText("Job Order");

        mnuCreateJobOrderMaster.setText("Create Job Order Master");
        mnuCreateJobOrderMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateJobOrderMasterActionPerformed(evt);
            }
        });
        mnuJobOrder.add(mnuCreateJobOrderMaster);
        mnuJobOrder.add(jSeparator8);

        mnuSearchJobOrder.setText("Search Job Order");
        mnuSearchJobOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSearchJobOrderActionPerformed(evt);
            }
        });
        mnuJobOrder.add(mnuSearchJobOrder);

        jMenuBar1.add(mnuJobOrder);

        mnuQuotations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/quotation_16px.png"))); // NOI18N
        mnuQuotations.setText("Quotations");

        mnuCreateQuotation.setText("Create Quotation");
        mnuCreateQuotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateQuotationActionPerformed(evt);
            }
        });
        mnuQuotations.add(mnuCreateQuotation);
        mnuQuotations.add(jSeparator4);

        mnuManageQuotation.setText("Search Quotation");
        mnuManageQuotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageQuotationActionPerformed(evt);
            }
        });
        mnuQuotations.add(mnuManageQuotation);

        jMenuBar1.add(mnuQuotations);

        mnuInvoices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/invoice_16px.png"))); // NOI18N
        mnuInvoices.setText("Invoices");

        mnuCreateInvoice.setText("Invoice1");
        mnuCreateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateInvoiceActionPerformed(evt);
            }
        });
        mnuInvoices.add(mnuCreateInvoice);

        mnuSearchInvoice1.setText("Search Invoice1");
        mnuSearchInvoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSearchInvoice1ActionPerformed(evt);
            }
        });
        mnuInvoices.add(mnuSearchInvoice1);
        mnuInvoices.add(jSeparator5);

        mnuCreateInvoice2.setText("Invoice2");
        mnuCreateInvoice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateInvoice2ActionPerformed(evt);
            }
        });
        mnuInvoices.add(mnuCreateInvoice2);

        mnuSearchInvoice2.setText("Search Invoice2");
        mnuSearchInvoice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSearchInvoice2ActionPerformed(evt);
            }
        });
        mnuInvoices.add(mnuSearchInvoice2);
        mnuInvoices.add(jSeparator7);

        mnuProformaInvoice.setText("Proforma Invoice");
        mnuProformaInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProformaInvoiceActionPerformed(evt);
            }
        });
        mnuInvoices.add(mnuProformaInvoice);

        mnuSearchProformaInvoice.setText("Search Proforma Invoice");
        mnuSearchProformaInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSearchProformaInvoiceActionPerformed(evt);
            }
        });
        mnuInvoices.add(mnuSearchProformaInvoice);

        jMenuBar1.add(mnuInvoices);

        mnuChallan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/challan_16px.png"))); // NOI18N
        mnuChallan.setText("Challan");

        mnuCreateChallan.setText("Create Challan");
        mnuCreateChallan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateChallanActionPerformed(evt);
            }
        });
        mnuChallan.add(mnuCreateChallan);
        mnuChallan.add(jSeparator6);

        mnuManageChallan.setText("Manage Challan");
        mnuManageChallan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageChallanActionPerformed(evt);
            }
        });
        mnuChallan.add(mnuManageChallan);

        jMenuBar1.add(mnuChallan);

        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/help_16px.png"))); // NOI18N
        mnuHelp.setText("Help");

        mnuLicenseDetails.setText("License Details");
        mnuHelp.add(mnuLicenseDetails);
        mnuHelp.add(jSeparator2);

        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1337, 831));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Function to check database connection
    private void mnuCreateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateInvoiceActionPerformed
        // TODO add your handling code here:
        CreateInvoice.getObj().setVisible( true );
    }//GEN-LAST:event_mnuCreateInvoiceActionPerformed

    private void mnuManageChallanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageChallanActionPerformed
        // TODO add your handling code here:
ManageChallan.getObj().setVisible( true);
    }//GEN-LAST:event_mnuManageChallanActionPerformed

    private void mnuManageCompanyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageCompanyDetailsActionPerformed
        // TODO add your handling code here:
        CompanyDetails.getObj().setVisible( true );
    }//GEN-LAST:event_mnuManageCompanyDetailsActionPerformed

    private void mnuManageClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageClientActionPerformed
        // TODO add your handling code here:
        ManageClients.getObj().setVisible( true );
    }//GEN-LAST:event_mnuManageClientActionPerformed

    private void mnuManageProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageProductActionPerformed
        // TODO add your handling code here:
        ManageProduct.getObj().setVisible( true );
    }//GEN-LAST:event_mnuManageProductActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState( JFrame.MAXIMIZED_BOTH );
        CurrentDate();
    }//GEN-LAST:event_formWindowOpened

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        System.exit( 0 );
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuCreateQuotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateQuotationActionPerformed
        // TODO add your handling code here:
        CreateQuotation.getObj().setVisible( true );
    }//GEN-LAST:event_mnuCreateQuotationActionPerformed

    private void mnuManageProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageProcessActionPerformed
        // TODO add your handling code here:
        ManageProcess.getObj().setVisible( true );
    }//GEN-LAST:event_mnuManageProcessActionPerformed

    private void mnuManageMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageMaterialActionPerformed
        // TODO add your handling code here:
        ManageMaterial.getObj().setVisible( true );
    }//GEN-LAST:event_mnuManageMaterialActionPerformed

    private void mnuCreateChallanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateChallanActionPerformed
        // TODO add your handling code here:
        CreateChallan.getObj().setVisible( true );
    }//GEN-LAST:event_mnuCreateChallanActionPerformed

    private void mnuCreateInvoice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateInvoice2ActionPerformed
        // TODO add your handling code here:
        CreateInvoice2.getObj().setVisible( true );
    }//GEN-LAST:event_mnuCreateInvoice2ActionPerformed

    private void mnuCreateJobOrderMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateJobOrderMasterActionPerformed
        // TODO add your handling code here:
        JobOrderMaster.getObj().setVisible( true );
    }//GEN-LAST:event_mnuCreateJobOrderMasterActionPerformed

    private void mnuProformaInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProformaInvoiceActionPerformed
        // TODO add your handling code here:
        CreateProformaInvoice.getObj().setVisible( true );
    }//GEN-LAST:event_mnuProformaInvoiceActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAboutActionPerformed

    private void mnuSearchInvoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSearchInvoice1ActionPerformed
        // TODO add your handling code here:
        SearchInvoice1.getObj().setVisible( true );
    }//GEN-LAST:event_mnuSearchInvoice1ActionPerformed

    private void mnuSearchInvoice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSearchInvoice2ActionPerformed
        // TODO add your handling code here:
        SearchInvoice2.getObj().setVisible( true );
    }//GEN-LAST:event_mnuSearchInvoice2ActionPerformed

    private void mnuSearchProformaInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSearchProformaInvoiceActionPerformed
        // TODO add your handling code here:
        SearchProformaInvoice.getObj().setVisible( true );
    }//GEN-LAST:event_mnuSearchProformaInvoiceActionPerformed

    private void mnuSearchJobOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSearchJobOrderActionPerformed
        // TODO add your handling code here:
        SearchJobOrder.getObj().setVisible( true );
    }//GEN-LAST:event_mnuSearchJobOrderActionPerformed

    private void mnuManageQuotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageQuotationActionPerformed
        // TODO add your handling code here:
        SearchQuotation.getObj().setVisible( true );
    }//GEN-LAST:event_mnuManageQuotationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals( info.getName() )) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger( Dashboard.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger( Dashboard.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger( Dashboard.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger( Dashboard.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable() {
            public void run() {
                new Dashboard().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JLabel lblConnectionStatus;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuChallan;
    private javax.swing.JMenu mnuClients;
    private javax.swing.JMenu mnuCompanyDetails;
    private javax.swing.JMenuItem mnuCreateChallan;
    private javax.swing.JMenuItem mnuCreateInvoice;
    private javax.swing.JMenuItem mnuCreateInvoice2;
    private javax.swing.JMenuItem mnuCreateJobOrderMaster;
    private javax.swing.JMenuItem mnuCreateQuotation;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuInvoices;
    private javax.swing.JMenu mnuJobOrder;
    private javax.swing.JMenuItem mnuLicenseDetails;
    private javax.swing.JMenuItem mnuManageChallan;
    private javax.swing.JMenuItem mnuManageClient;
    private javax.swing.JMenuItem mnuManageCompanyDetails;
    private javax.swing.JMenuItem mnuManageMaterial;
    private javax.swing.JMenuItem mnuManageProcess;
    private javax.swing.JMenuItem mnuManageProduct;
    private javax.swing.JMenuItem mnuManageQuotation;
    private javax.swing.JMenu mnuMaterial;
    private javax.swing.JMenu mnuProcess;
    private javax.swing.JMenu mnuProducts;
    private javax.swing.JMenuItem mnuProformaInvoice;
    private javax.swing.JMenu mnuQuotations;
    private javax.swing.JMenuItem mnuSearchInvoice1;
    private javax.swing.JMenuItem mnuSearchInvoice2;
    private javax.swing.JMenuItem mnuSearchJobOrder;
    private javax.swing.JMenuItem mnuSearchProformaInvoice;
    // End of variables declaration//GEN-END:variables
}
