/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job.work.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sunny
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("LOGO.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCompanyDetails = new javax.swing.JMenu();
        mnuManageCompanyDetails = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        mnuClients = new javax.swing.JMenu();
        mnuManageClient = new javax.swing.JMenuItem();
        mnuProducts = new javax.swing.JMenu();
        mnuManageProduct = new javax.swing.JMenuItem();
        mnuSearch = new javax.swing.JMenu();
        mnuQuotations = new javax.swing.JMenu();
        mnuCreateQuotation = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuManageQuotation = new javax.swing.JMenuItem();
        mnuInvoices = new javax.swing.JMenu();
        mnuCreateInvoice = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuManageInvoice = new javax.swing.JMenuItem();
        mnuChallan = new javax.swing.JMenu();
        mnuCreateChallan = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuManageChallan = new javax.swing.JMenuItem();
        mnuPayments = new javax.swing.JMenu();
        mnuManagePayments = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("S. I. GEARS - Job Work Management  System");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/dashlogo_1.png"))); // NOI18N
        jLabel1.setText("JOB WORK MANAGEMENT SYSTEM");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Version 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1295, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        mnuCompanyDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/factory_16px.png"))); // NOI18N
        mnuCompanyDetails.setText("Company Details");

        mnuManageCompanyDetails.setText("Manage Company Details");
        mnuManageCompanyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageCompanyDetailsActionPerformed(evt);
            }
        });
        mnuCompanyDetails.add(mnuManageCompanyDetails);
        mnuCompanyDetails.add(jSeparator1);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuCompanyDetails.add(mnuExit);

        jMenuBar1.add(mnuCompanyDetails);

        mnuClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/client_management_16px.png"))); // NOI18N
        mnuClients.setText("Clients");

        mnuManageClient.setText("Manage Client");
        mnuManageClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageClientActionPerformed(evt);
            }
        });
        mnuClients.add(mnuManageClient);

        jMenuBar1.add(mnuClients);

        mnuProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/products_16px.png"))); // NOI18N
        mnuProducts.setText("Products");

        mnuManageProduct.setText("Manage Product");
        mnuManageProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageProductActionPerformed(evt);
            }
        });
        mnuProducts.add(mnuManageProduct);

        jMenuBar1.add(mnuProducts);

        mnuSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/search_16px.png"))); // NOI18N
        mnuSearch.setText("Search");
        jMenuBar1.add(mnuSearch);

        mnuQuotations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/quotation_16px.png"))); // NOI18N
        mnuQuotations.setText("Quotations");

        mnuCreateQuotation.setText("Create Quotation");
        mnuCreateQuotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateQuotationActionPerformed(evt);
            }
        });
        mnuQuotations.add(mnuCreateQuotation);
        mnuQuotations.add(jSeparator4);

        mnuManageQuotation.setText("Manage Quotation");
        mnuQuotations.add(mnuManageQuotation);

        jMenuBar1.add(mnuQuotations);

        mnuInvoices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/invoice_16px.png"))); // NOI18N
        mnuInvoices.setText("Invoices");

        mnuCreateInvoice.setText("Create Invoice");
        mnuCreateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateInvoiceActionPerformed(evt);
            }
        });
        mnuInvoices.add(mnuCreateInvoice);
        mnuInvoices.add(jSeparator5);

        mnuManageInvoice.setText("Manage Invoice");
        mnuInvoices.add(mnuManageInvoice);

        jMenuBar1.add(mnuInvoices);

        mnuChallan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/challan_16px.png"))); // NOI18N
        mnuChallan.setText("Challan");

        mnuCreateChallan.setText("Create Challan");
        mnuChallan.add(mnuCreateChallan);
        mnuChallan.add(jSeparator6);

        mnuManageChallan.setText("Manage Challan");
        mnuManageChallan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageChallanActionPerformed(evt);
            }
        });
        mnuChallan.add(mnuManageChallan);

        jMenuBar1.add(mnuChallan);

        mnuPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/payment_16px.png"))); // NOI18N
        mnuPayments.setText("Payments");

        mnuManagePayments.setText("Manage Payments");
        mnuPayments.add(mnuManagePayments);

        jMenuBar1.add(mnuPayments);

        mnuReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/job/work/images/report_16px.png"))); // NOI18N
        mnuReports.setText("Reports");
        jMenuBar1.add(mnuReports);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1337, 831));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCreateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCreateInvoiceActionPerformed

    private void mnuManageChallanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageChallanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManageChallanActionPerformed

    private void mnuManageCompanyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageCompanyDetailsActionPerformed
        // TODO add your handling code here:
        CompanyDetails.getObj().setVisible(true);
    }//GEN-LAST:event_mnuManageCompanyDetailsActionPerformed

    private void mnuManageClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageClientActionPerformed
        // TODO add your handling code here:
        ManageClients.getObj().setVisible(true);
    }//GEN-LAST:event_mnuManageClientActionPerformed

    private void mnuManageProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageProductActionPerformed
        // TODO add your handling code here:
        ManageProduct.getObj().setVisible(true);
    }//GEN-LAST:event_mnuManageProductActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuCreateQuotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateQuotationActionPerformed
        // TODO add your handling code here:
        CreateQuotation.getObj().setVisible(true);
    }//GEN-LAST:event_mnuCreateQuotationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenu mnuChallan;
    private javax.swing.JMenu mnuClients;
    private javax.swing.JMenu mnuCompanyDetails;
    private javax.swing.JMenuItem mnuCreateChallan;
    private javax.swing.JMenuItem mnuCreateInvoice;
    private javax.swing.JMenuItem mnuCreateQuotation;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuInvoices;
    private javax.swing.JMenuItem mnuManageChallan;
    private javax.swing.JMenuItem mnuManageClient;
    private javax.swing.JMenuItem mnuManageCompanyDetails;
    private javax.swing.JMenuItem mnuManageInvoice;
    private javax.swing.JMenuItem mnuManagePayments;
    private javax.swing.JMenuItem mnuManageProduct;
    private javax.swing.JMenuItem mnuManageQuotation;
    private javax.swing.JMenu mnuPayments;
    private javax.swing.JMenu mnuProducts;
    private javax.swing.JMenu mnuQuotations;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuSearch;
    // End of variables declaration//GEN-END:variables
}
