/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job.work.management.system;

/**
 *
 * @author sunny
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCompanyDetails = new javax.swing.JMenu();
        mnuManageCompanyDetails = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        mnuClients = new javax.swing.JMenu();
        mnuAddClient = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuManageClient = new javax.swing.JMenuItem();
        mnuProducts = new javax.swing.JMenu();
        mnuAddProduct = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuManageProduct = new javax.swing.JMenuItem();
        mnuSearch = new javax.swing.JMenu();
        mnuQuotations = new javax.swing.JMenu();
        mnuCreateQuotation = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuManageQuotation = new javax.swing.JMenuItem();
        mnuInvoices = new javax.swing.JMenu();
        mnuCreateInvoice = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuManageInvoice = new javax.swing.JMenuItem();
        mnuChallan = new javax.swing.JMenu();
        mnuCreateChallan = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuManageChallan = new javax.swing.JMenuItem();
        mnuPayments = new javax.swing.JMenu();
        mnuManagePayments = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job Work Management  System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1319, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );

        mnuCompanyDetails.setText("Company Details");

        mnuManageCompanyDetails.setText("Manage Company Details");
        mnuManageCompanyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageCompanyDetailsActionPerformed(evt);
            }
        });
        mnuCompanyDetails.add(mnuManageCompanyDetails);
        mnuCompanyDetails.add(jSeparator1);

        mnuExit.setText("Exit");
        mnuCompanyDetails.add(mnuExit);

        jMenuBar1.add(mnuCompanyDetails);

        mnuClients.setText("Clients");

        mnuAddClient.setText("Add Client");
        mnuAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddClientActionPerformed(evt);
            }
        });
        mnuClients.add(mnuAddClient);
        mnuClients.add(jSeparator2);

        mnuManageClient.setText("Manage Client");
        mnuClients.add(mnuManageClient);

        jMenuBar1.add(mnuClients);

        mnuProducts.setText("Products");

        mnuAddProduct.setText("Add Product");
        mnuAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddProductActionPerformed(evt);
            }
        });
        mnuProducts.add(mnuAddProduct);
        mnuProducts.add(jSeparator3);

        mnuManageProduct.setText("Manage Product");
        mnuProducts.add(mnuManageProduct);

        jMenuBar1.add(mnuProducts);

        mnuSearch.setText("Search");
        jMenuBar1.add(mnuSearch);

        mnuQuotations.setText("Quotations");

        mnuCreateQuotation.setText("Create Quotation");
        mnuQuotations.add(mnuCreateQuotation);
        mnuQuotations.add(jSeparator4);

        mnuManageQuotation.setText("Manage Quotation");
        mnuQuotations.add(mnuManageQuotation);

        jMenuBar1.add(mnuQuotations);

        mnuInvoices.setText("Invoices");

        mnuCreateInvoice.setText("Create Invoice");
        mnuCreateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateInvoiceActionPerformed(evt);
            }
        });
        mnuInvoices.add(mnuCreateInvoice);
        mnuInvoices.add(jSeparator5);

        mnuManageInvoice.setText("Manage Invoice");
        mnuInvoices.add(mnuManageInvoice);

        jMenuBar1.add(mnuInvoices);

        mnuChallan.setText("Challan");

        mnuCreateChallan.setText("Create Challan");
        mnuChallan.add(mnuCreateChallan);
        mnuChallan.add(jSeparator6);

        mnuManageChallan.setText("Manage Challan");
        mnuManageChallan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageChallanActionPerformed(evt);
            }
        });
        mnuChallan.add(mnuManageChallan);

        jMenuBar1.add(mnuChallan);

        mnuPayments.setText("Payments");

        mnuManagePayments.setText("Manage Payments");
        mnuPayments.add(mnuManagePayments);

        jMenuBar1.add(mnuPayments);

        mnuReports.setText("Reports");
        jMenuBar1.add(mnuReports);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1337, 831));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCreateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCreateInvoiceActionPerformed

    private void mnuManageChallanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageChallanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManageChallanActionPerformed

    private void mnuManageCompanyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageCompanyDetailsActionPerformed
        // TODO add your handling code here:
        CompanyDetails.getObj().setVisible(true);
    }//GEN-LAST:event_mnuManageCompanyDetailsActionPerformed

    private void mnuAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddClientActionPerformed
        // TODO add your handling code here:
        AddClient.getObj().setVisible(true);
    }//GEN-LAST:event_mnuAddClientActionPerformed

    private void mnuAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddProductActionPerformed
        // TODO add your handling code here:
        AddProduct.getObj().setVisible(true);
    }//GEN-LAST:event_mnuAddProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem mnuAddClient;
    private javax.swing.JMenuItem mnuAddProduct;
    private javax.swing.JMenu mnuChallan;
    private javax.swing.JMenu mnuClients;
    private javax.swing.JMenu mnuCompanyDetails;
    private javax.swing.JMenuItem mnuCreateChallan;
    private javax.swing.JMenuItem mnuCreateInvoice;
    private javax.swing.JMenuItem mnuCreateQuotation;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuInvoices;
    private javax.swing.JMenuItem mnuManageChallan;
    private javax.swing.JMenuItem mnuManageClient;
    private javax.swing.JMenuItem mnuManageCompanyDetails;
    private javax.swing.JMenuItem mnuManageInvoice;
    private javax.swing.JMenuItem mnuManagePayments;
    private javax.swing.JMenuItem mnuManageProduct;
    private javax.swing.JMenuItem mnuManageQuotation;
    private javax.swing.JMenu mnuPayments;
    private javax.swing.JMenu mnuProducts;
    private javax.swing.JMenu mnuQuotations;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuSearch;
    // End of variables declaration//GEN-END:variables
}
